apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronus
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cronus
  template:
    metadata:
      labels:
        app: cronus
    spec:
      containers:
        - name: cronus
          image: cronus:latest
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: cronus-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: cronus
  ports:
    - port: 8080
      targetPort: 8080
