---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronus
  namespace: cronus
spec:
  selector:
    matchLabels:
      app: cronus
  replicas: 1
  template:
    metadata:
      labels:
        app: cronus
    spec:
      serviceAccountName: cronus
      containers:
      - name: cronus
        image: nickkeers/cronus:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http