apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-cronjobs
  namespace: default
subjects:
  - kind: ServiceAccount
    name: cronus-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: cronjob-reader
  apiGroup: rbac.authorization.k8s.io
