apiVersion: v1
kind: Service
metadata:
  name: cronus
  namespace: cronus
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    com.docker.project: cronus
  type: LoadBalancer